@startuml

title Sculptor's Assistant

left to right direction

actor Скульптор
actor LightApi
actor Користувач
actor Продавець
actor Техпідтримка
actor PaymentApi


rectangle {

    usecase (Отримати інформацію про освітлення)
    usecase (Налаштувати освітлення) 
    usecase (Отримати рекомендації) 
    usecase (Замовити інструменти)
    usecase (Оплатити товар)
    usecase (Отримати відповіді на питання)
    usecase (Авторизувати користувача)
    usecase (Обробити замовлення)
    usecase (Надати технічну підтримку)
    
    Скульптор -- (Отримати інформацію про освітлення)
    Скульптор -- (Налаштувати освітлення)
    Скульптор -- (Отримати рекомендації)
    Скульптор -- (Замовити інструменти)
    Скульптор -- (Оплатити товар)
    Скульптор -- (Отримати відповіді на питання)
    (Отримати інформацію про освітлення) -- LightApi
    (Авторизувати користувача) -- Користувач
    (Обробити замовлення) -- Продавець
    (Надати технічну підтримку) -- Техпідтримка
    (Оплатити товар) -- PaymentApi
    
    (Отримати інформацію про освітлення) .> (Авторизувати користувача): include
    (Налаштувати освітлення) .> (Авторизувати користувача) : include\n\n\n\n\t\t\t\t\t
    (Отримати рекомендації) .> (Авторизувати користувача) : include\n\n\n\n\n\t\t\t
    (Замовити інструменти).> (Авторизувати користувача): include\n\n\n\t\t\t
    (Оплатити товар) .> (Авторизувати користувача): include\n\n\n\t\t\t
    (Отримати відповіді на питання) .> (Авторизувати користувача): include\n\n\n\t\t\t
    (Обробити замовлення) .> (Авторизувати користувача): include\n\n\n\n\t\t\t
    (Надати технічну підтримку) .> (Авторизувати користувача): include\n\n\n\n\t\t\t
    Скульптор --|> Користувач
    Продавець --|> Користувач
    Техпідтримка --|> Користувач
}

@enduml
